### ISSUE TITLE
Set up the petfinder JS SDK in your project

### ISSUE THREAD

**Issue by chrisbendel** [CSI-280/playdogplay#2]
https://github.com/petfinder-com/petfinder-js-sdk

Use this to interact with the petfinder API. This will handle authentication automatically for you, so you don't have to handle re-authing whenever your token times out (this will save you a huge headache, trust me)

Integrate this into the project, probably smart to set this up as an exported constant value like this

```
export const pf = new petfinder.Client({apiKey: "my-api-key", secret: "my-api-secret"});
```
then, in another file
```
import {pf} from '../path/to/pf.js';
```

key & secret i set up are here
```
Key: HB4E0LPBodtgXJlBVOYvZSDaxgGSCA7Li7Eq6tqb6uVDRfzAp4
Secret: ACCq1YmJ2XzZxT6WrvbSU9voepnbCllw0NmSF363
```

**Comment by TAwc** [comment]
the api is currently fully working in master and authorized on the react branch

**Comment by chrisbendel** [comment]
ready to be closed/
